// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Crudapplication.Models;

public partial class Employee
{
    public int id { get; set; }

    public string name { get; set; }

    public string department { get; set; }

    public string position { get; set; }
}