// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace Crudapplication.Models;

public partial class Employee2DbContext : DbContext
{
    public Employee2DbContext(DbContextOptions<Employee2DbContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Employee> Employees { get; set; }

 
}