// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace Crudapplication.Models;

public partial class Employee2DbContext : DbContext
{
    public Employee2DbContext(DbContextOptions<Employee2DbContext> options)
        : base(options)
    {
    }

    public virtual DbSet<EmployeesTable> EmployeesTables { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<EmployeesTable>(entity =>
        {
            entity.HasKey(e => e.id).HasName("PK__Employee__3213E83F2AEE9EB6");

            entity.ToTable("EmployeesTable");

            entity.Property(e => e.department)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.name)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.position)
                .IsRequired()
                .HasMaxLength(100);
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}